// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (CreateTransactionRow, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteTransaction(ctx context.Context, arg DeleteTransactionParams) error
	GetTransactionByID(ctx context.Context, id int32) (GetTransactionByIDRow, error)
	GetTransactions(ctx context.Context) ([]GetTransactionsRow, error)
	GetTransactionsByUserID(ctx context.Context, userID *int32) ([]GetTransactionsByUserIDRow, error)
	GetTransactionsByUserIDAndType(ctx context.Context, arg GetTransactionsByUserIDAndTypeParams) ([]GetTransactionsByUserIDAndTypeRow, error)
	GetUserAccountInfo(ctx context.Context, id int32) (GetUserAccountInfoRow, error)
	GetUserBalance(ctx context.Context, id int32) (pgtype.Numeric, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int32) (User, error)
	UpdateUserBalance(ctx context.Context, arg UpdateUserBalanceParams) error
}

var _ Querier = (*Queries)(nil)
